### ISSUE TITLE
No good way to construct an expression "... like ... escape ..."

### ISSUE THREAD

**Issue by EugineKosenko** [magit/emacsql#10]
I need something like

<code>select url from links where url like '"%\%%"' escape '\';</code>

However, the construction like

<pre><code>
(emacsql-compile storage
 [:select url
  :from links
  :where (like url (escape "%\\%%" "\\"))])
</code></pre>

returns

<code>"SELECT url FROM links WHERE url LIKE '\"%\\%%\"' ESCAPE '\"\\\"';"</code>

And the sqlite query parser detects the error: the ESCAPE argument must be a single character, not a string.

**Comment by skeeto** [comment]
Yup, this is definitely an issue since EmacSQL doesn't offer a way to
pass strings without printing them. Unfortunately I haven't figured out
how I want to change the interface to cover situations like this. I'm
open to input on the matter.

In the meantime you can work around it by passing your own SQL string
directly in place of a SQL s-expression, though you'll be responsible
for your own bind parameters.

**Comment by EugineKosenko** [comment]
> In the meantime you can work around it by passing your own SQL string directly in place of a SQL s-expression

I do it in the way, but it seems like an escape workaround. This is the only case I've stuck now, and I hope, this will not be so often. I think we must keep in mind this case, however.

**Comment by ak-coram** [comment]
@skeeto: I think this issue can be closed since there's now basic support for `escape` via #50.
