### ISSUE TITLE
emacsql-process does not return a process on the built-in connection

### ISSUE THREAD

**Issue by akirak** [magit/emacsql#112]
I am using `emacsql-sqlite` from a library.

After a recent update, `emacsql-process` returns a connection, and not a process, on a connection created by `emacsql-sqlite-builtin`.

To reproduce, the following expression returned a process before, but it now returns a connection (e.g. `#<sqlite db=0xafa2878 name=/directory/sample.db>`).

```emacs-lisp
(emacsql-process (emacsql-sqlite-builtin "sample.db"))
```

If this was an API change, a documentation would be nice. At present, the generic function has no documentation.

**Comment by tarsius** [comment]
Thanks for the report! I've tried to address it in 7c533fb6c27c3a10b6ab05bddf663e37c109e459. Please read that first.

> If this was an API change, a documentation would be nice. At present, the generic function has no documentation.

This wasn't considered part of the API and I avoided replacing "process" with something more accurate, because I only consider this an internal naming inconsistency and wanted to avoid the risk that comes with changing it.

If you need to access this slot for some reason, then please point me to the code. I might be able to advice you how to avoid that, or maybe I have to add some feature to EmacSQL.

I plan to create a new EmacSQL release soon, and will contact downstreams here before doing that. Until then, you can find the most recent roadmap at https://github.com/melpa/melpa/commit/4872ef038dbbf67008bfa7951574ee372d6ff68d.

**Comment by akirak** [comment]
Thank you for your quick response.

> This wasn't considered part of the API 

Makes sense. It turns out that my relevant code is unnecessary now (as long as it uses the builtin backend). I manage sqlite connections by myself but used `set-process-query-on-exit-flag` to automatically close the processes on exit. Good to know that there is no process any more.
