### ISSUE TITLE
Mismatch between emacsql-sqlite.el and the removal of C files in sqlite/

### ISSUE THREAD

**Issue by DamienCassou** [magit/emacsql#125]
Hi,

commit https://github.com/magit/emacsql/commit/7a79c2be3da818b7e14a53b9f29e44ac27236c0a removed the `sqlite/` folder and its C files. Still `emacsql-sqlite.el` references these files in the `emacsql-sqlite-compile` function. I don't really understand how `emacsql-sqlite.el` is supposed to work without these C files.

Best

**Comment by tarsius** [comment]
The idea was to remove this file (and function) too. I've done that now.

Only two SQLite back-ends remain: `emacsql-sqlite-builtin`, which uses the built-in SQLite support added in Emacs 29.1, and `emacsql-sqlite-module`, which uses the module provided by the third-party `sqlite3` package.

These back-ends are more reliable and faster than the original `emacsql-sqlite` backend, which used a custom-build executable.

I forgot to remove `emacsql-sqlite` because the commit's first version was created more than two years ago, or so, and at that time parts of `emacsql-sqlite.el` were still needed (because the common parts had not been moved to `emacsql-common.el` yet. Also none of the tests failed due to the obsolete library still lingering around.

But thanks for reporting this! Would have been more embarrassing if the next release still contained the file.

**Comment by DamienCassou** [comment]
thank you very much
