### ISSUE TITLE
Error compiling emacsql-sqlite on Windows when `.emacs.d` is in a path with non-ASCII characters

### ISSUE THREAD

**Issue by skrytebane** [magit/emacsql#77]
I know it's a terrible idea, but I have a non-ASCII character in my user folder on Windows 10, and it's breaking `emacsql-sqlite-compile` when attempting compilation with Mingw-gcc, installed from w64devkit. That is, it will complain about being unable to open various files under `elpa/emacsql-sqlite`, like `sqlite.c`.

At first I thought it was because there's a space in my user folder (another terrible idea), but now I think it's because of the non-ASCII character.

`*Compile-Log*` emits something like this:

```
c:/opt/w64devkit/bin/cc.exe -Ic:/Users/Silly Üser/AppData/Roaming/.emacs.d/elpa/emacsql-sqlite-20190727.1710/sqlite -O2 -DSQLITE_THREADSAFE=0 -DSQLITE_DEFAULT_FOREIGN_KEYS=1 -DSQLITE_ENABLE_FTS5 -DSQLITE_ENABLE_FTS4 -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_RTREE -DSQLITE_ENABLE_JSON1 -DSQLITE_SOUNDEX c:/Users/Silly Üser/AppData/Roaming/.emacs.d/elpa/emacsql-sqlite-20190727.1710/sqlite/sqlite3.c c:/Users/Silly Üser/AppData/Roaming/.emacs.d/elpa/emacsql-sqlite-20190727.1710/sqlite/emacsql.c -o c:/Users/Silly Üser/AppData/Roaming/.emacs.d/elpa/emacsql-sqlite-20190727.1710/sqlite/emacsql-sqlite.exe
cc1.exe: fatal error: c:/Users/Silly Üser/AppData/Roaming/.emacs.d/elpa/emacsql-sqlite-20190727.1710/sqlite/sqlite3.c: No such file or directory
compilation terminated.
cc1.exe: fatal error: c:/Users/Silly Üser/AppData/Roaming/.emacs.d/elpa/emacsql-sqlite-20190727.1710/sqlite/emacsql.c: No such file or directory
compilation terminated.
```

It works if I run it from the Git-Bash-shell, so I'm able to work around this for myself, but I'm not (yet) sure how to best fix this, so I thought I would leave this issue here to make it googlable for others with the same problem.

**Comment by skeeto** [comment]
This is an interesting multi-layer problem. I have a solution for your 
specific problem, and an idea for a workaround of the general problem. 
Before getting into the details, here's the solution:

Set coding-system-for-write to windows-1252. Otherwise it triggers a bug 
in Emacs's call-process function which results this error.

Details: I was careful to not invoke a shell when building SQLite from 
Emacs specifically to avoid exactly this sort of problem. However, there 
are two compounding problems on Windows:

1. Emacs doesn't support passing Unicode strings as subprocess arguments.

2. GCC doesn't accept Unicode strings as arguments.

The first is due to Emacs' limited support on Windows, and the second is 
the usual Windows nonsense, specifically that nobody has ever written 
decent C or C++ standard libraries for Windows.

As for (1), call-process ultimately invokes CreateProcessA which only 
accepts an "ANSI" (read: windows-1252) command string. The encoding for 
arguments depends on the value of coding-system-for-write.

* If nil, the raw-text coding system it used. Unibyte strings are passed 
as-is, multibyte strings are encoded with UTF-8. The latter is always 
wrong on Windows and Emacs must not do this. Passing through unibyte 
strings is reasonable since these are essentially just byte strings that 
are presumably already encoding something.

* If non-nil, that coding system is used. The only valid coding system for 
arguments on Windows is windows-1252. Passing UTF-8 makes no sense since 
receivers must not expect to receive UTF-8.

If Emacs is going to use CreateProcessA it must ignore any coding system 
configuration and only use windows-1252. These are strictly "ANSI" 
strings. However, should really be using CreateProcessW in the first 
place, encoding arguments using only UTF-16, still ignoring coding system 
configuration.

As for (2), unfortunately even if you use CreateProcessW, Microsoft 
decided programs that ask for an "ANSI" argument string should be silently 
given a mangled, useless form of the Unicode argument string. Most console 
programs on Windows — including GCC — behave poorly with non-ASCII 
arguments and file names because every C and C++ standard library hooks up 
to the "ANSI" Win32 interface rather than the Unicode interface. So even 
if Emacs did the right thing, arguments still would not work correctly for 
most C and C++ programs.

EmacSQL itself just has plain ASCII file names. To avoid anything but 
ASCII file names it could use relative rather than absolute paths when 
invoking the compiler. That's my workaround idea. This should sidestep all 
these issues for EmacSQL.

The path you listed here has one non-ASCII character — Ü, U+00DC, LATIN 
CAPITAL LETTER U WITH DIARESIS. This happens to be representable in 
Windows-1252 (encoded as byte 0xDC), and so it should work fine with 
Windows' "ANSI" interfaces. However, Emacs' "helpful" encoding of 
multibyte arguments to UTF-8 (byte sequence 0xC3 0x9C) destroys this 
convenient property.

Curiously in your log the file name survives the trip back out of GCC and 
into Emacs' log buffer as an exact match for the passed argument. It's as 
though the file name successfully made a round trip, so why didn't it 
work? Emacs encodes U+00DC to 0xC3 0x9C. GCC passes this to fopen() or 
whatever, which passes it to CreateFileA(). This interface strictly 
accepts Windows-1252, which means it sees "Ãœ" (U+00C3 U+0153). This file 
doesn't exist, and so GCC fails to open the file. It then prints its 
original argument to standard error. Emacs decodes the output of GCC as 
UTF-8, decoding 0xC3 0x9C back into the original U+00DC.

I'm guessing somehow running via Git Bash:

* Changes or sets the coding system.
* Changes how "Ü" is interpreted by Emacs. (In some cases it evaluates to 
a multibyte string, in some cases to a unibyte string.)
* Changes the tools. (different Emacs? different GCC?)

**Comment by skrytebane** [comment]
I was thinking about using relative paths, but wasn't sure if you would find it too hacky.

Seeing how broken it seems, though, I think maybe this would be the best solution, and it avoids a bunch of platform-specific conditional code, since it should just work on any platform.

**Comment by RenlefuX** [comment]
https://github.com/nobiot/emacsql-sqlite.exe/      nobiot may provided a good solution for this issue.
